[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version= '0.8.29'
fuzz = { runs = 1_000 }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@chimera/=lib/chimera/src/"
]

optimizer = true
optimizer_runs = 200

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
eth_mainnet = "${ETH_MAINNET_RPC_URL}"